# Generated by Django 5.0.4 on 2024-04-08 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('domicilio', models.CharField(blank=True, max_length=250)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(choices=[('femenino', 'Femenino'), ('masculino', 'Masculino'), ('otro', 'Otro')], max_length=10)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('nombre_completo',),
            },
        ),
        migrations.CreateModel(
            name='EstadoSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_discapacitado', models.BooleanField(default=False)),
                ('posee_desnutricion', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='persona.persona')),
            ],
        ),
    ]
